// <auto-generated />
using FoodMart.Models.Infrastucture;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodMart.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodMart.Models.Infrastucture.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("FoodMart.Models.Infrastucture.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 100m,
                            ImageLink = "https://klike.net/uploads/posts/2022-09/1662040170_j-50.jpg",
                            Name = "Яблоко"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 150m,
                            ImageLink = "https://media.baamboozle.com/uploads/images/119504/1666966541_1034289_gif-url.jpeg",
                            Name = "Банан"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 500m,
                            ImageLink = "https://cojo.ru/wp-content/uploads/2023/01/granat-bez-kostochek-1.webp",
                            Name = "Гранат"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 400m,
                            ImageLink = "https://ketokotleta.ru/wp-content/uploads/3/d/8/3d82223993fa9b0adf0be050b0e682e7.png",
                            Name = "Груша"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 300m,
                            ImageLink = "https://catherineasquithgallery.com/uploads/posts/2021-03/1614548312_46-p-apelsin-na-belom-fone-61.jpg",
                            Name = "Апельсин"
                        });
                });

            modelBuilder.Entity("FoodMart.Models.Infrastucture.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FoodMart.Models.Infrastucture.Cart", b =>
                {
                    b.HasOne("FoodMart.Models.Infrastucture.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodMart.Models.Infrastucture.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
